app = "enffly"

primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "gunicorn -w 1 -k gthread --threads 4 -b 0.0.0.0:8080 upload_api:app"
  worker = "python worker.py"

[http_service]
  internal_port = 8080
  processes = ["web"]
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

[[mounts]]
  source = "data"
  destination = "/data"
