app = "enffly"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "gunicorn -w 1 -k gthread --threads 2 -b 0.0.0.0:8080 app:app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1   # â¬… BITNO za peak
  processes = ["app"]

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
