app = "enffly-worker"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[processes]
  worker = "python worker.py"

kill_signal = "SIGINT"
kill_timeout = 10

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
